[package]
name = "sonic-nodes"
version = "0.1.0"
edition = "2021"
license = "MIT"
author = ["Clemens Tiedt <clemens.tiedt@student.hpi.de>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
cpal = "0.13"